alter table public.luma_submissions
  add column if not exists review_message text,
  add column if not exists status_updated_at timestamptz not null default now(),
  add column if not exists approved_at timestamptz,
  add column if not exists rejected_at timestamptz;

create table if not exists public.luma_submission_status_history (
  id bigint generated by default as identity primary key,
  submission_id uuid not null references public.luma_submissions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null,
  review_message text,
  created_at timestamptz not null default now()
);

create index if not exists luma_submission_status_history_submission_id_idx
  on public.luma_submission_status_history(submission_id, created_at);

alter table public.luma_submission_status_history enable row level security;

drop policy if exists "Developers can read own submission history" on public.luma_submission_status_history;
create policy "Developers can read own submission history"
  on public.luma_submission_status_history
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.track_luma_submission_status()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and (
    new.status is distinct from old.status
    or new.review_message is distinct from old.review_message
  ) then
    new.status_updated_at := now();

    if new.status = 'Approved' and new.status is distinct from old.status then
      new.approved_at := now();
      new.rejected_at := null;
    elsif new.status = 'Rejected' and new.status is distinct from old.status then
      new.rejected_at := now();
      new.approved_at := null;
    elsif new.status not in ('Approved', 'Rejected') and new.status is distinct from old.status then
      new.approved_at := null;
      new.rejected_at := null;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists luma_submission_status_tracking_before on public.luma_submissions;
create trigger luma_submission_status_tracking_before
before update on public.luma_submissions
for each row execute function public.track_luma_submission_status();

create or replace function public.log_luma_submission_status_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.luma_submission_status_history (
      submission_id, user_id, status, review_message, created_at
    ) values (
      new.id, new.user_id, coalesce(new.status, 'Pending'), new.review_message,
      coalesce(new.submitted_at, now())
    );
  elsif new.status is distinct from old.status
     or new.review_message is distinct from old.review_message then
    insert into public.luma_submission_status_history (
      submission_id, user_id, status, review_message, created_at
    ) values (
      new.id, new.user_id, coalesce(new.status, 'Pending'), new.review_message, now()
    );
  end if;
  return new;
end;
$$;

revoke all on function public.log_luma_submission_status_history() from public, anon, authenticated;

drop trigger if exists luma_submission_status_history_after on public.luma_submissions;
create trigger luma_submission_status_history_after
after insert or update on public.luma_submissions
for each row execute function public.log_luma_submission_status_history();

insert into public.luma_submission_status_history (
  submission_id, user_id, status, review_message, created_at
)
select s.id, s.user_id, coalesce(s.status, 'Pending'), s.review_message,
       coalesce(s.status_updated_at, s.submitted_at, now())
from public.luma_submissions s
where s.user_id is not null
  and not exists (
    select 1 from public.luma_submission_status_history h
    where h.submission_id = s.id
  );;
