-- Luma Store developer submission status tracking
-- Run this migration in the Supabase SQL editor or through the Supabase CLI.

alter table public.luma_submissions
  add column if not exists review_message text,
  add column if not exists status_updated_at timestamptz not null default now(),
  add column if not exists approved_at timestamptz,
  add column if not exists rejected_at timestamptz;

create table if not exists public.luma_submission_status_history (
  id bigint generated by default as identity primary key,
  submission_id uuid not null references public.luma_submissions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null,
  review_message text,
  created_at timestamptz not null default now()
);

create index if not exists luma_submission_status_history_submission_id_idx
  on public.luma_submission_status_history(submission_id, created_at);

alter table public.luma_submission_status_history enable row level security;

drop policy if exists "Developers can read own submission history" on public.luma_submission_status_history;
create policy "Developers can read own submission history"
  on public.luma_submission_status_history
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Update timestamps before the row is stored.
create or replace function public.prepare_luma_submission_status()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.status_updated_at := coalesce(new.status_updated_at, now());
    return new;
  end if;

  if new.status is distinct from old.status
     or new.review_message is distinct from old.review_message then
    new.status_updated_at := now();
  end if;

  if new.status is distinct from old.status then
    if new.status = 'Approved' then
      new.approved_at := now();
      new.rejected_at := null;
    elsif new.status = 'Rejected' then
      new.rejected_at := now();
      new.approved_at := null;
    else
      new.approved_at := null;
      new.rejected_at := null;
    end if;
  end if;

  return new;
end;
$$;

-- Write the timeline only after the parent submission row exists.
create or replace function public.record_luma_submission_status_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.luma_submission_status_history (
      submission_id,
      user_id,
      status,
      review_message,
      created_at
    ) values (
      new.id,
      new.user_id,
      new.status,
      new.review_message,
      coalesce(new.submitted_at, now())
    );
  elsif new.status is distinct from old.status
     or new.review_message is distinct from old.review_message then
    insert into public.luma_submission_status_history (
      submission_id,
      user_id,
      status,
      review_message,
      created_at
    ) values (
      new.id,
      new.user_id,
      new.status,
      new.review_message,
      now()
    );
  end if;

  return null;
end;
$$;

drop trigger if exists luma_submission_status_tracking on public.luma_submissions;
drop trigger if exists luma_submission_status_prepare on public.luma_submissions;
drop trigger if exists luma_submission_status_history on public.luma_submissions;

create trigger luma_submission_status_prepare
before insert or update on public.luma_submissions
for each row execute function public.prepare_luma_submission_status();

create trigger luma_submission_status_history
after insert or update on public.luma_submissions
for each row execute function public.record_luma_submission_status_history();

-- Backfill one timeline entry for existing submissions that do not have history yet.
insert into public.luma_submission_status_history (
  submission_id,
  user_id,
  status,
  review_message,
  created_at
)
select
  s.id,
  s.user_id,
  s.status,
  s.review_message,
  coalesce(s.status_updated_at, s.submitted_at, now())
from public.luma_submissions s
where not exists (
  select 1
  from public.luma_submission_status_history h
  where h.submission_id = s.id
);
